swagger: '2.0'
info:
  title: "Library API"
  description: "This is a API to manage a Library"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header

#* Mechanics Endpoints
paths: 
  /mechanics/login:
    post:
      tags:
        - "Mechanics"
      summary: "Login Endpoint, (generates token)"
      description: "Validates mechanic credentials, generates and returns a number specific token"
      parameters:
        - in: "body"
          name: "body"
          description: "Login credentials"
          required: true
          schema:
            $ref: "#/definitions/LoginCredentials"
      responses:
        200:
          description: "Successful Login"
          schema:
            $ref: "#/definitions/LoginResponse"
          examples:
            application/json:
              token: "kjsbvpluahsenASDKLJASDKBASKDHI..."
              message: "Login successful"
              status: "success"

  /mechanics:
    post:
        tags:
          - "Mechanics"
        summary: "Endpoint to create a new mechanic"
        description: "Endpoint to create a new mechanic in our mechanic shop system, email must be unique"
        parameters:
          - in: "body"
            name: "body"
            description: "Information to create a new mechanic"
            required: true
            schema:
              $ref: "#/definitions/CreateMechanicPayload"
        responses:
          201:
            description: "Created Mechanics Successfully"
            schema:
              $ref: "#/definitions/AllMechanics"
            examples:
              application/json:
                id: 1
                name: "John Doe"
                address: "123 Main St"
                email: "johndoe@gmail.com"
                password: "password123"

    get:
        tags:
          - "Mechanics"
        summary: "Returns all Mechanics"
        description: "Endpoint to retrieve an array of all mechanics in the system"
        parameters:
          - in: query
            name: page
            type: integer
            description: "Page number for pagination (optional)"
          - in: query
            name: per_page
            type: integer
            default: 10
            description: Items perpage (default 10)
        responses:
          201:
            description: "Successful Mechanic Creation"
            schema:
              $ref: "#/definitions/AllMechanics"
            examples:
              application/json:
                id: 1
                name: "John Doe"
                address: "123 Main St"
                email: "johndoe@gmail.com"
                password: "password123"
    put:
        tags:
          - "Mechanics"
        summary: "Endpoit to update a mechanic"
        description: "Endpoint to update a mechanic, this is a token authenticated route, and the mechanic must be logged in to update their account"
        security:
          - bearerAuth: []
        parameters:
          - in: 'body'
            name: 'body'
            description: "information required to update a mechanic"
            required: true
            schema:
              $ref: "#/definitions/UpdateMechanicPayload"
        responses:
          200:
            description: "Successfully updated mechanic"
            schema:
              $ref: "#/definitions/UpdateMechanicResponse"
            examples:
              application/json:
                id: 1
                name: "Dohn Joe"
                address: "321 Main St"
                email: "dohnjoe@gmail.com"
                password: "password123"

    delete:
        tags:
          - "Mechanics"
        summary: "Endpoint to delete a mechanic"
        description: "Endpoint to delete a mechanic, Requires token authentication, mechanic must be logged in to delete their account"
        security:
          - bearerAuth: []
        responses:
          201:
            description: "Mechanic Successfully Deleted"
            schema:
              $ref: "#/definitions/DeleteMechanicResponse"
            examples:
              application/json:
                message: "Successfully deleted mechanic <mechanic_id>"
#* Customers Endpoints

  /customers:
    post:
        tags:
          - "Customers"
        summary: "Endpoint to create a new customer"
        description: "Endpoint to create a new customer in our mechanic shop system, email must be unique"
        parameters:
          - in: "body"
            name: "body"
            description: "Information to create a new customer"
            required: true
            schema:
              $ref: "#/definitions/CreateCustomerPayload"
        responses:
          201:
            description: "Created Customer Successfully"
            schema:
              $ref: "#/definitions/AllCustomers"
            examples:
              application/json:
                id: 1
                name: "John Doe"
                email: "johndoe@gmail.com"
                phone: "1234567890"

    get:
        tags:
          - "Customers"
        summary: "Returns all Customers"
        description: "Endpoint to retrieve an array of all customers in the system"
        parameters:
          - in: query
            name: page
            type: integer
            description: "Page number for pagination (optional)"
          - in: query
            name: per_page
            type: integer
            default: 10
            description: Items perpage (default 10)
        responses:
          201:
            description: "Successful Customers Creation"
            schema:
              $ref: "#/definitions/AllCustomers"
            examples:
              application/json:
                id: 1
                name: "John Doe"
                email: "johndoe@gmail.com"
                phone: "1234567890"
    put:
        tags:
          - "Customers"
        summary: "Endpoit to update a customer"
        description: "Endpoint to update a customer."
        security:
          - bearerAuth: []
        parameters:
          - in: 'body'
            name: 'body'
            description: "information required to update a customer"
            required: true
            schema:
              $ref: "#/definitions/UpdateCustomerPayload"
        responses:
          200:
            description: "Successfully updated customer"
            schema:
              $ref: "#/definitions/UpdateCustomerResponse"
            examples:
              application/json:
                id: 1
                name: "Dohn Joe"
                email: "dohnjoe@gmail.com"
                phone: "0987654321"

    delete:
        tags:
          - "Customers"
        summary: "Endpoint to delete a customer"
        description: "Endpoint to delete a custoner."
        security:
          - bearerAuth: []
        responses:
          201:
            description: "Customer Successfully Deleted"
            schema:
              $ref: "#/definitions/DeleteCustomerResponse"
            examples:
              application/json:
                message: "Successfully deleted customer <customer_id>"
 


definitions: 
  
  LoginCredentials:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
    required:
      - email
      - password
    
  LoginResponse:
    type: "object"
    properties:
      token:
        type: "string"
      message:
        type: "string"
      status:
        type: "string"


  CreateMechanicPayload:
    type: "object"
    properties:
      name:
        type: "string"
      address:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
    required:
      - name
      - address
      - email
      - password


  CreateMechanicResponse:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      address:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"


  AllMechanics:
    type: "array"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      address:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"


  UpdateMechanicPayload:
    type: "object"
    properties:
      name:
        type: 'string'
      address: 
        type: 'string'
      email:
        type: 'string'
      password:
        type: 'string'

    required:
      - name
      - address
      - email
      - password


  UpdateMechanicResponse:
    type: 'object'
    properties:
      id:
        type: 'integer'
      name:
        type: 'string'
      address:
        type: 'string'
      email:
        type: 'string'
      password:
        type: 'string'

    
  DeleteMechanic:
    type: 'object'
    properties:
      message:
        type: "string"

#* Customers
  CreateCustomerPayload:
    type: "object"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
    required:
      - name
      - email
      - phone


  CreateCustomerResponse:
    type: "object"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
    required:
      - name
      - email
      - phone


  AllCustomers:
    type: "array"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"  


  UpdateCustomerPayload:
    type: "object"
    properties:
      name:
        type: 'string'
      email:
        type: 'string'
      phone:
        type: 'string'

    required:
      - name
      - email
      - phone


  UpdateCustomerResponse:
    type: "object"
    properties:
      name:
        type: 'string'
      email:
        type: 'string'
      phone:
        type: 'string'

    
  DeleteCustomer:
    type: 'object'
    properties:
      message:
        type: "string"

